import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lessons_sidebar: [
    {
      type: 'category',
      label: 'Informatique',
      items: [
        {
          type: 'category',
          label: 'Bases',
          items: [
            {
              type: 'autogenerated',
              dirName: 'info/bases'
            },
          ]
        },
      ]
    },

    {
      type: 'category',
      label: 'Management',
      items: [
        {
          type: 'category',
          label: 'SI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/si'
            },
          ]
        },
        {
          type: 'category',
          label: 'Agilité',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/agile'
            },
          ]
        },
        {
          type: 'category',
          label: 'Sobriété Numérique',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/sobriete'
            },
          ]
        }
      ],
    },

    {
      type: 'category',
      label: 'Modélisation & Gestion',
      items: [
        {
          type: 'category',
          label: 'UI/UX',
          items: [
            {
              type: 'autogenerated',
              dirName: 'gestion_modelisation/ui_ux'
            },
          ]
        },
      ]
    }
  ],
};

export default sidebars;
