import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lessons_sidebar: [
    {
      type: 'category',
      label: 'Informatique',
      items: [
        {
          type: 'category',
          label: 'Bases',
          items: [
            {
              type: 'autogenerated',
              dirName: 'info/bases',
            },
          ]
        },
        {
          type: 'category',
          label: 'DevOps',
          items: [
            {
              type: 'category',
              label: 'Introduction',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'info/devops/intro',
                },
              ],
            },
          ]
        },
        {
          type: 'category',
          label: 'Base de Données',
          items: [
            {
              type: 'autogenerated',
              dirName: 'info/bdd',
            },
          ]
        }
      ]
    },

    {
      type: 'category',
      label: 'Management',
      items: [
        {
          type: 'category',
          label: 'SI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/si'
            },
          ]
        },
        {
          type: 'category',
          label: 'Agilité',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/agile'
            },
          ]
        },
        {
          type: 'category',
          label: 'Sobriété Numérique',
          items: [
            {
              type: 'autogenerated',
              dirName: 'management/sobriete'
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Gestion & Modélisation Projet',
      items: [
        {
          type: 'autogenerated',
          dirName: 'gestion_modelisation',
        },
      ]
    },
    {
      type: 'category',
      label: 'Tronc Commun',
      items: [
        {
          type: 'doc',
          label: 'Conduite du Changement',
          id: 'tronc_commun/change_management/index'
        }
      ]
    }
  ],
};

export default sidebars;
